// actionTypes.js
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

export const FETCH_PRODUCTS_BY_CATEGORY_REQUEST = "FETCH_PRODUCTS_BY_CATEGORY_REQUEST";
export const FETCH_PRODUCTS_BY_CATEGORY_SUCCESS = "FETCH_PRODUCTS_BY_CATEGORY_SUCCESS";
export const FETCH_PRODUCTS_BY_CATEGORY_FAILURE = "FETCH_PRODUCTS_BY_CATEGORY_FAILURE";
export const FETCH_PRODUCTS_BY_SUBCATEGORY_REQUEST="FETCH_PRODUCTS_BY_SUBCATEGORY_REQUEST"
export const FETCH_PRODUCTS_BY_SUBCATEGORY_SUCCESS = "FETCH_PRODUCTS_BY_SUBCATEGORY_SUCCESS";
export const FETCH_PRODUCTS_BY_SUBCATEGORY_FAILURE = "FETCH_PRODUCTS_BY_SUBCATEGORY_FAILURE";

// Define similar request, success, and failure action types for fetching products by subcategory


export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE";


export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";



export const USER_LOGOUT = "USER_LOGOUT";



export const CART_REQUEST = "cart/request";
export const CART_FAILURE = "cart/failure";
export const GET_CART_SUCCESS = "get/cart/success";
export const DELETE_CART_SUCCESS = "delete/cart/success";
export const UPDATE_CART_ITEM_QUANTITY = 'UPDATE_CART_ITEM_QUANTITY';
